"""empty message

Revision ID: 554f2a99d5a0
Revises: 
Create Date: 2023-02-01 17:43:02.457302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554f2a99d5a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
